"""ScienceQA multimodal data loading, chat-template tokenisation, and collation.

Region Segmentation
-------------------
Each token receives a **region_id** that identifies its role:

    0 = prompt    (system + multimodal user turn: image tokens + question + choices)
    1 = reasoning (assistant rationale/explanation before `####`)
    2 = answer    (`####` and final multiple-choice answer letter)

Prompt tokens (including special visual tokens <|image_pad|>, etc.) have labels = -100,
ensuring that KD losses (FKL/RKL) and CE operate exclusively on the text reasoning and
answer tokens.

Supports two data pathways:
* Off-policy teacher CoT (`build_dataloader_cot`): reads records generated by
  scripts/generate_scienceqa_cot.py (Phase 1.1 JSONL).
* Human rationale baseline (`build_dataloader_human_rationale`): uses ScienceQA
  native `lecture` + `solution` as the reasoning turn.
"""

from __future__ import annotations

import json
import os
import random
from typing import Any, Dict, List, Optional, Tuple

import datasets
import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset
try:
    from PIL import Image
except ImportError:
    Image = None

# ------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------
REGION_PROMPT    = 0
REGION_REASONING = 1
REGION_ANSWER    = 2

SYSTEM_PROMPT = (
    "You are a helpful assistant that answers science questions. "
    "Think step by step, explain your reasoning clearly, "
    "then provide your final answer after ####."
)

ANSWER_LETTERS = "ABCDE"
HASH_MARKER = "####"


# ------------------------------------------------------------------
# Dataset Loading & Formatting Helpers
# ------------------------------------------------------------------

def load_scienceqa(split: str = "train") -> datasets.Dataset:
    """Load ScienceQA from Hugging Face (`derek-thomas/ScienceQA`)."""
    ds = datasets.load_dataset("derek-thomas/ScienceQA", split=split)
    return ds


def format_choices(choices: List[str]) -> str:
    """Format multiple choice options as (A) ..., (B) ..."""
    return "\n".join(
        f"({ANSWER_LETTERS[i]}) {c}" for i, c in enumerate(choices)
    )


def answer_index_to_letter(index: int) -> str:
    """Convert 0-based integer index to option letter (0 -> 'A', 1 -> 'B', etc.)."""
    if 0 <= index < len(ANSWER_LETTERS):
        return ANSWER_LETTERS[index]
    raise ValueError(f"Invalid answer index {index}; expected 0..{len(ANSWER_LETTERS)-1}")


def answer_letter_to_index(letter: str) -> int:
    """Convert letter ('A'-'E') to 0-based integer index."""
    idx = ANSWER_LETTERS.find(letter.strip().upper())
    if idx >= 0:
        return idx
    raise ValueError(f"Invalid answer letter {letter!r}; expected one of {ANSWER_LETTERS}")


# ------------------------------------------------------------------
# Chat Message Builders
# ------------------------------------------------------------------

def build_user_message(
    question: str,
    choices: List[str],
    image: Optional[Any] = None,
    hint: str = "",
) -> dict:
    """Build a multimodal user message conforming to Qwen2.5-VL chat schema."""
    prompt_text = f"Question: {question}\n\nChoices:\n{format_choices(choices)}"
    if hint and hint.strip():
        prompt_text = f"Hint: {hint.strip()}\n\n{prompt_text}"

    content = []
    if image is not None:
        if Image is not None and isinstance(image, Image.Image):
            content.append({"type": "image", "image": image})
        elif Image is None:
            content.append({"type": "image", "image": image})
    content.append({"type": "text", "text": prompt_text})

    return {"role": "user", "content": content}


def build_assistant_message(reasoning: str, answer_letter: str) -> dict:
    """Build assistant response message with reasoning and #### answer marker."""
    text = f"{reasoning.strip()}\n{HASH_MARKER} {answer_letter.strip().upper()}"
    return {"role": "assistant", "content": text}


def build_full_messages(
    question: str,
    choices: List[str],
    reasoning: str,
    answer_letter: str,
    image: Optional[Image.Image] = None,
    hint: str = "",
) -> List[dict]:
    """Build the complete list of chat messages (system, user, assistant)."""
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        build_user_message(question, choices, image, hint),
        build_assistant_message(reasoning, answer_letter),
    ]


# ------------------------------------------------------------------
# Tokenisation with Region Segmentation
# ------------------------------------------------------------------

def tokenise_scienceqa_example(
    example: Dict[str, Any],
    processor: Any,
    max_length: int = 1536,
) -> Optional[Dict[str, Any]]:
    """Tokenise a single ScienceQA example with region segmentation.

    Parameters
    ----------
    example : dict
        Must contain ``question``, ``choices``, ``answer`` (or ``answer_gold_letter``),
        and ``teacher_full_text`` (or ``lecture``/``solution``).
        May contain ``image`` (PIL.Image or None) and ``hint``.
    processor : AutoProcessor (Qwen2_5_VLProcessor)
    max_length : int

    Returns
    -------
    dict with keys:
        ``input_ids``: [L] int tensor
        ``attention_mask``: [L] int tensor
        ``labels``: [L] int tensor (prompt masked to -100)
        ``region_ids``: [L] int tensor (0=prompt, 1=reasoning, 2=answer)
        ``has_image``: bool
        and optionally:
        ``pixel_values``: [num_patches, patch_dim] tensor
        ``image_grid_thw``: [1, 3] tensor
    or None if example is empty or invalid.
    """
    try:
        from qwen_vl_utils import process_vision_info
    except ImportError:
        raise ImportError("qwen-vl-utils is required. Install via `pip install qwen-vl-utils`.")

    question = example.get("question", "")
    choices = example.get("choices", [])
    if not question or not choices:
        return None

    # Determine gold answer letter
    if "answer_gold_letter" in example and example["answer_gold_letter"]:
        answer_letter = example["answer_gold_letter"].strip().upper()
    elif "answer" in example:
        ans_raw = example["answer"]
        if isinstance(ans_raw, int):
            answer_letter = answer_index_to_letter(ans_raw)
        else:
            answer_letter = str(ans_raw).strip().upper()
    else:
        return None

    # Determine reasoning text
    reasoning = example.get("teacher_full_text", "")
    if not reasoning:
        lecture = example.get("lecture", "") or ""
        solution = example.get("solution", "") or ""
        reasoning = f"{lecture}\n{solution}".strip()
    if not reasoning:
        return None

    # Handle image
    image = example.get("image", None)
    if image is None and example.get("image_path"):
        img_p = example["image_path"]
        if os.path.isfile(img_p):
            try:
                image = Image.open(img_p).convert("RGB")
            except Exception:
                image = None

    if image is not None:
        if Image is not None and not isinstance(image, Image.Image):
            if isinstance(image, str) and os.path.isfile(image):
                try:
                    image = Image.open(image).convert("RGB")
                except Exception:
                    image = None
            else:
                image = None

    hint = example.get("hint", "") or ""
    has_image = image is not None

    messages = build_full_messages(
        question=question,
        choices=choices,
        reasoning=reasoning,
        answer_letter=answer_letter,
        image=image,
        hint=hint,
    )

    # 1. Full text via chat template
    full_text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False
    )

    # 2. Extract vision inputs
    image_inputs, video_inputs = process_vision_info(messages)

    # 3. Process full inputs through processor
    processed = processor(
        text=[full_text],
        images=image_inputs,
        videos=video_inputs,
        padding=False,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )

    input_ids = processed["input_ids"].squeeze(0)          # [L]
    attention_mask = processed["attention_mask"].squeeze(0)  # [L]
    seq_len = input_ids.shape[0]

    # 4. Determine prompt boundary
    prompt_messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        build_user_message(question, choices, image, hint),
    ]
    prompt_text = processor.apply_chat_template(
        prompt_messages, tokenize=False, add_generation_prompt=True
    )
    prompt_image_inputs, prompt_video_inputs = process_vision_info(prompt_messages)
    prompt_processed = processor(
        text=[prompt_text],
        images=prompt_image_inputs,
        videos=prompt_video_inputs,
        padding=False,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )
    prompt_len = min(prompt_processed["input_ids"].shape[1], seq_len)

    # 5. Build labels: mask prompt tokens (-100)
    labels = input_ids.clone()
    labels[:prompt_len] = -100

    # 6. Locate '####' separator to divide reasoning (1) from answer (2)
    # The assistant response starts at prompt_len.
    hash_marker_token_ids = processor.tokenizer.encode(HASH_MARKER, add_special_tokens=False)
    answer_start = seq_len  # default fallback

    # Scan for hash_marker in input_ids[prompt_len:]
    k = len(hash_marker_token_ids)
    if k > 0:
        for pos in range(prompt_len, seq_len - k + 1):
            if input_ids[pos: pos + k].tolist() == hash_marker_token_ids:
                answer_start = pos
                break

    # If exact token match failed, fallback to text decode search
    if answer_start == seq_len and prompt_len < seq_len:
        resp_decoded = processor.tokenizer.decode(input_ids[prompt_len:])
        marker_pos = resp_decoded.find(HASH_MARKER)
        if marker_pos >= 0:
            pre_marker = resp_decoded[:marker_pos]
            pre_marker_ids = processor.tokenizer.encode(pre_marker, add_special_tokens=False)
            answer_start = min(prompt_len + len(pre_marker_ids), seq_len)

    # 7. Build region_ids
    region_ids = torch.full((seq_len,), REGION_PROMPT, dtype=torch.long)
    if answer_start > prompt_len:
        region_ids[prompt_len:answer_start] = REGION_REASONING
    if answer_start < seq_len:
        region_ids[answer_start:] = REGION_ANSWER

    result = {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
        "region_ids": region_ids,
        "has_image": has_image,
    }

    if "pixel_values" in processed and processed["pixel_values"] is not None:
        result["pixel_values"] = processed["pixel_values"].squeeze(0)  # [patches, dim]
    if "image_grid_thw" in processed and processed["image_grid_thw"] is not None:
        result["image_grid_thw"] = processed["image_grid_thw"]          # [1, 3] or [num_images, 3]

    return result


# ------------------------------------------------------------------
# Multimodal Dynamic Padding Collator
# ------------------------------------------------------------------

class MultimodalKDCollator:
    """Dynamic padding collator for multimodal KD batches.

    Collates:
    - ``input_ids`` padded with ``pad_token_id``
    - ``attention_mask`` padded with 0
    - ``labels`` padded with -100
    - ``region_ids`` padded with -1
    - ``has_image`` boolean tensor [B]
    - ``pixel_values`` stacked/concatenated along batch dim if any image exists
    - ``image_grid_thw`` concatenated along batch dim if any image exists
    """

    def __init__(self, pad_token_id: int, max_length: int = 1536):
        assert pad_token_id is not None, "pad_token_id cannot be None."
        self.pad_token_id = pad_token_id
        self.max_length = max_length

    def __call__(self, batch: List[Dict[str, Any]]) -> Dict[str, Any]:
        # Filter out any None entries
        valid_examples = [ex for ex in batch if ex is not None]
        if not valid_examples:
            raise ValueError("All examples in the batch are None or invalid.")

        batch_max = min(
            max(ex["input_ids"].shape[0] for ex in valid_examples),
            self.max_length,
        )

        input_ids_list = []
        attention_mask_list = []
        labels_list = []
        region_ids_list = []
        has_image_list = []

        pixel_values_list = []
        image_grid_thw_list = []
        any_image = any(ex.get("has_image", False) and "pixel_values" in ex for ex in valid_examples)

        for ex in valid_examples:
            seq_len = min(ex["input_ids"].shape[0], batch_max)
            pad_len = batch_max - seq_len

            input_ids_list.append(
                torch.cat([
                    ex["input_ids"][:seq_len],
                    torch.full((pad_len,), self.pad_token_id, dtype=torch.long),
                ])
            )
            attention_mask_list.append(
                torch.cat([
                    ex["attention_mask"][:seq_len],
                    torch.zeros(pad_len, dtype=torch.long),
                ])
            )
            labels_list.append(
                torch.cat([
                    ex["labels"][:seq_len],
                    torch.full((pad_len,), -100, dtype=torch.long),
                ])
            )
            region_ids_list.append(
                torch.cat([
                    ex["region_ids"][:seq_len],
                    torch.full((pad_len,), -1, dtype=torch.long),
                ])
            )
            has_image_list.append(ex.get("has_image", False))

            if any_image and "pixel_values" in ex and ex["pixel_values"] is not None:
                pv = ex["pixel_values"]
                if pv.ndim == 1:
                    pv = pv.unsqueeze(0)
                pixel_values_list.append(pv)

            if any_image and "image_grid_thw" in ex and ex["image_grid_thw"] is not None:
                thw = ex["image_grid_thw"]
                if thw.ndim == 1:
                    thw = thw.unsqueeze(0)
                image_grid_thw_list.append(thw)

        collated = {
            "input_ids": torch.stack(input_ids_list),
            "attention_mask": torch.stack(attention_mask_list),
            "labels": torch.stack(labels_list),
            "region_ids": torch.stack(region_ids_list),
            "has_image": torch.tensor(has_image_list, dtype=torch.bool),
        }

        if any_image and pixel_values_list:
            collated["pixel_values"] = torch.cat(pixel_values_list, dim=0)
            collated["image_grid_thw"] = torch.cat(image_grid_thw_list, dim=0)

        # Sanity assertion: labels must be -100 wherever attention_mask == 0
        assert (collated["labels"][collated["attention_mask"] == 0] == -100).all(), (
            "Collator invariant violated: pad tokens must have labels = -100."
        )

        return collated


# ------------------------------------------------------------------
# PyTorch Dataset Wrappers & DataLoader Builders
# ------------------------------------------------------------------

class ScienceQACoTDataset(Dataset):
    """Memory-friendly Dataset wrapper for ScienceQA CoT."""

    def __init__(
        self,
        records: List[Dict[str, Any]],
        processor: Any,
        max_length: int = 1536,
    ):
        self.records = records
        self.processor = processor
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        rec = self.records[idx]
        item = tokenise_scienceqa_example(rec, self.processor, self.max_length)
        if item is None:
            fallback_ids = torch.full((4,), self.processor.tokenizer.pad_token_id, dtype=torch.long)
            return {
                "input_ids": fallback_ids,
                "attention_mask": torch.zeros(4, dtype=torch.long),
                "labels": torch.full((4,), -100, dtype=torch.long),
                "region_ids": torch.full((4,), -1, dtype=torch.long),
                "has_image": False,
            }
        return item


def build_dataloader_cot(
    processor: Any,
    max_length: int,
    batch_size: int,
    jsonl_path: str,
    split: str = "train",
    filter_teacher_wrong: bool = False,
    filter_no_separator: bool = True,
    micro_overfit_n: Optional[int] = None,
    shuffle: bool = True,
    seed: int = 42,
) -> DataLoader:
    """Build DataLoader from teacher-generated ScienceQA CoT JSONL."""
    if not os.path.isfile(jsonl_path):
        raise FileNotFoundError(
            f"ScienceQA CoT JSONL not found: {jsonl_path!r}. "
            f"Generate it first via scripts/generate_scienceqa_cot.py"
        )

    records: List[Dict[str, Any]] = []
    n_total = 0
    n_dropped_sep = 0
    n_dropped_wrong = 0

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            n_total += 1
            if r.get("split") != split:
                continue
            if filter_no_separator and not r.get("separator_found", False):
                n_dropped_sep += 1
                continue
            if filter_teacher_wrong and not r.get("is_teacher_correct", False):
                n_dropped_wrong += 1
                continue
            records.append(r)

    if micro_overfit_n is not None:
        records = records[:micro_overfit_n]

    print(
        f"[data] ScienceQA CoT split={split}: {len(records)} records loaded "
        f"(total_in_file={n_total}, dropped_no_sep={n_dropped_sep}, "
        f"dropped_wrong={n_dropped_wrong})"
    )

    dataset = ScienceQACoTDataset(records, processor, max_length=max_length)
    collator = MultimodalKDCollator(
        pad_token_id=processor.tokenizer.pad_token_id,
        max_length=max_length,
    )

    g = torch.Generator()
    g.manual_seed(seed)

    def _worker_init_fn(worker_id: int) -> None:
        worker_seed = (seed + worker_id) & 0xFFFFFFFF
        random.seed(worker_seed)
        np.random.seed(worker_seed)
        torch.manual_seed(worker_seed)

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        collate_fn=collator,
        num_workers=2,
        pin_memory=True,
        generator=g,
        worker_init_fn=_worker_init_fn,
        drop_last=False,
    )


def build_dataloader_human_rationale(
    processor: Any,
    max_length: int,
    batch_size: int,
    split: str = "train",
    micro_overfit_n: Optional[int] = None,
    shuffle: bool = True,
    seed: int = 42,
) -> DataLoader:
    """Build DataLoader using human rationale (`lecture` + `solution`) directly from ScienceQA."""
    ds = load_scienceqa(split=split)

    records = []
    for idx, ex in enumerate(ds):
        lecture = ex.get("lecture", "") or ""
        solution = ex.get("solution", "") or ""
        reasoning = f"{lecture}\n{solution}".strip()
        if not reasoning:
            continue

        records.append({
            "split": split,
            "idx": idx,
            "question": ex["question"],
            "choices": ex["choices"],
            "answer": ex["answer"],
            "image": ex.get("image", None),
            "hint": ex.get("hint", "") or "",
            "teacher_full_text": reasoning,
            "separator_found": True,
            "is_teacher_correct": True,
        })

    if micro_overfit_n is not None:
        records = records[:micro_overfit_n]

    print(f"[data] ScienceQA Human Rationale split={split}: {len(records)} records loaded")

    dataset = ScienceQACoTDataset(records, processor, max_length=max_length)
    collator = MultimodalKDCollator(
        pad_token_id=processor.tokenizer.pad_token_id,
        max_length=max_length,
    )

    g = torch.Generator()
    g.manual_seed(seed)

    def _worker_init_fn(worker_id: int) -> None:
        worker_seed = (seed + worker_id) & 0xFFFFFFFF
        random.seed(worker_seed)
        np.random.seed(worker_seed)
        torch.manual_seed(worker_seed)

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        collate_fn=collator,
        num_workers=2,
        pin_memory=True,
        generator=g,
        worker_init_fn=_worker_init_fn,
        drop_last=False,
    )
